### ISSUE TITLE
Changing the name of this repo to "Theme Acceptance Test" instead of "Theme Unit Test"

### ISSUE THREAD

**Issue by overclokk** [WPTT/theme-test-data#68]
This is a proposal to change the name of this repository for better reflect what it does because this is more a user front-end test and not a unit test -> https://en.wikipedia.org/wiki/Acceptance_testing

I know the file is as a decade old but when I read unit test this confusing me and the risk of feeding wrong terminologies in young developers is high.

**Comment by joyously** [comment]
How about Theme Test Data instead?

**Comment by overclokk** [comment]
Yes, you're right, the data is not **an acceptance** test but is **for acceptance** test, and now that I think about it better maybe "Theme Dummy Data" could better explain the intent of the repo. (trimmed out also the word test)

What do you think?

**Comment by carolinan** [comment]
perhaps simply "demo content"

**Comment by overclokk** [comment]
"Demo Content" also sounds right.

**Comment by overclokk** [comment]
Adding more:

"Sample content"
"Sample data"
"Dummy content"

**Comment by pbking** [comment]
"Test Site Content" is how I reference this handy bundle of content in my personal notes

**Comment by premanshup** [comment]
perhaps "Sample Theme Data"

**Comment by wmaouad** [comment]
The word "Test" is not wrong as long as it's not coupled with "Unit", in this case. I can see it validly be named `Wordpress Test Data`, as much as the other (good) suggestions.

The words `Sample`, `Test`, and `Dummy` lend the same signification to the `Data` or `Content` that is generated.

A very verbose variant could be `Sample Data for WordPress Theme Testing`

**Comment by emiluzelac** [comment]
Theme Unit Test is actually the proper name and this link would explain it https://www.testorigen.com/unit-testing-the-path-to-test-unit/

Since the content is meant for testing, we can’t call it demo, dummy or content data.

Unit testing has been around for a long time and current name was chosen for a reason. 

Making Theme Unit Test Data shorter makes sense and it’s up to you folks to determine what this will be, but I vote that we retain the words “Unit Test”.

**Comment by emiluzelac** [comment]
> This is a proposal to change the name of this repository for better reflect what it does because this is more a user front-end test and not a unit test -> https://en.wikipedia.org/wiki/Acceptance_testing
> 
> I know the file is as a decade old but when I read unit test this confusing me and the risk of feeding wrong terminologies in young developers is high.

I work at Envato and for Theme Forest. For the past 5 years, I’ve reviewed 30,000+ themes and without a single incident of confusion.

**Comment by kafleg** [comment]
During the themes team [meeting](https://wordpress.slack.com/archives/C02RP4Y3K/p1618326673090100), we finalized the name **Theme Test Data**
